const express = require("express");
const auth = require("./auth");
const provinces = require("./provinces");
const districts = require("./districts");
const substations = require("./substations");
const installations = require("./installations");
const readings = require("./readings");
const router = express.Router();
router.use(auth);
router.use(provinces);
router.use(districts);
router.use(substations);
router.use(readings);
router.use(installations);
module.exports = router;
